name: CD - Deploy DEV

on:
  push:
    branches: ["master"]
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy to DEV env
    uses: nttoan26/devops/.github/workflows/CD_java_k8s.yaml@v2
    with:
      environment: dev
      namespace: default
      stack: java
      platform: k8s
      container_name: knote
    secrets: inherit 
