name: CD - Deploy QA

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to QA env
    uses: nttoan26/devops/.github/workflows/CD_java_k8s.yaml@v2
    with:
      environment: qa
      namespace: default
      stack: java
      platform: k8s
      container_name: knote
    secrets: inherit
